### ISSUE TITLE
能提供下数据集吗？

### ISSUE THREAD

**Issue by gdtydm** [gugug/Hmm-NERTagger#2]
我最近想研究些分词相关的算法，能提供下这儿数据集吗？

**Comment by gugug** [comment]
您好，这边是连接
https://pan.baidu.com/s/1xc2ROMSq_ez74P_wa-ls_w

**Comment by gugug** [comment]
您好，这边是连接
https://pan.baidu.com/s/1xc2ROMSq_ez74P_wa-ls_w

**Comment by gugug** [comment]
https://pan.baidu.com/s/1xc2ROMSq_ez74P_wa-ls_w

**Comment by gdtydm** [comment]
非常感谢

**Comment by pandigreat** [comment]
同求分享一下数据集，谢谢
