### ISSUE TITLE
请求提供一下试验用的数据集

### ISSUE THREAD

**Issue by pandigreat** [gugug/Hmm-NERTagger#3]
能提供一下试验用的dataset吗？谢谢

**Comment by gugug** [comment]
你好，这是数据源。
链接: https://pan.baidu.com/s/1cWUADh198I0Z5fd2Ufw4cA 
提取码: jftj

**Comment by pandigreat** [comment]
> 你好，这是数据源。
> 链接: https://pan.baidu.com/s/1cWUADh198I0Z5fd2Ufw4cA
> 提取码: jftj

好的， 非常感谢
